export const ADMIN_PERMISSION_GROUPS = {
  dashboardView: ["dashboard:view"],
  calendarView: ["calendar:view"],
  profileView: ["profile:view"],
  showcaseView: ["showcase:view"],
  usersView: ["user:view", "user:edit", "user:role:manage", "user:import"],
  usersEdit: ["user:edit"],
  usersRoleManage: ["user:role:manage"],
  usersImport: ["user:import"],
  usersManage: ["user:edit", "user:role:manage", "user:import"],
  rbacView: ["rbac:view", "rbac:manage"],
  rbacManage: ["rbac:manage"],
  readingsView: [
    "reading:view",
    "reading:image:view",
    "reading:update",
    "reading:validate",
    "reading:flag",
    "reading:reject",
    "reading:task:create",
  ],
  readingsImageView: ["reading:image:view"],
  readingEventsView: ["reading-event:view", "audit:view"],
  readingsEditPage: ["reading:update", "reading:validate", "reading:flag", "reading:reject"],
  readingsUpdate: ["reading:update"],
  readingsValidate: ["reading:validate"],
  readingsFlag: ["reading:flag"],
  readingsReject: ["reading:reject"],
  readingTaskCreate: ["reading:task:create"],
  readingsManage: ["reading:update", "reading:validate", "reading:flag", "reading:reject"],
  historyView: ["history:view", "audit:view"],
  consumptionView: ["consumption:view"],
  metersView: ["meter:view", "meter:create", "meter:edit", "meter:import"],
  metersCreate: ["meter:create"],
  metersEdit: ["meter:edit"],
  metersManage: ["meter:create", "meter:edit", "meter:import"],
  metersImport: ["meter:import"],
  tasksView: [
    "task:view",
    "task:create",
    "task:update",
    "task:assign",
    "task:comment",
    "task:attachment:manage",
    "task:item:manage",
  ],
  tasksCreate: ["task:create"],
  tasksUpdate: ["task:update"],
  tasksAssign: ["task:assign"],
  tasksComment: ["task:comment"],
  tasksAttachmentManage: ["task:attachment:manage"],
  tasksItemManage: ["task:item:manage"],
  tasksEditPage: ["task:update", "task:assign"],
  tasksManage: [
    "task:update",
    "task:assign",
    "task:comment",
    "task:attachment:manage",
    "task:item:manage",
  ],
  billingOverviewView: [
    "billing:view",
    "billing:city:view",
    "billing:city:manage",
    "billing:zone:view",
    "billing:zone:manage",
    "billing:contract:view",
    "billing:contract:manage",
    "billing:tariff:view",
    "billing:tariff:manage",
    "billing:campaign:view",
    "billing:campaign:manage",
    "billing:campaign:generate",
    "billing:campaign:issue",
    "billing:invoice:view",
    "billing:invoice:issue",
    "billing:invoice:cancel",
    "billing:invoice:payment:create",
    "billing:invoice:delivery:create",
  ],
  billingEntry: [
    "billing:view",
    "billing:city:view",
    "billing:city:manage",
    "billing:zone:view",
    "billing:zone:manage",
    "billing:contract:view",
    "billing:contract:manage",
    "billing:tariff:view",
    "billing:tariff:manage",
    "billing:campaign:view",
    "billing:campaign:manage",
    "billing:campaign:generate",
    "billing:campaign:issue",
    "billing:invoice:view",
    "billing:invoice:issue",
    "billing:invoice:cancel",
    "billing:invoice:payment:create",
    "billing:invoice:delivery:create",
  ],
  billingCitiesView: ["billing:city:view", "billing:city:manage"],
  billingCitiesManage: ["billing:city:manage"],
  billingZonesView: ["billing:zone:view", "billing:zone:manage"],
  billingZonesManage: ["billing:zone:manage"],
  billingContractsView: ["billing:contract:view", "billing:contract:manage"],
  billingContractsManage: ["billing:contract:manage"],
  billingTariffsView: ["billing:tariff:view", "billing:tariff:manage"],
  billingTariffsManage: ["billing:tariff:manage"],
  billingCampaignsView: [
    "billing:campaign:view",
    "billing:campaign:manage",
    "billing:campaign:generate",
    "billing:campaign:issue",
  ],
  billingCampaignsManage: ["billing:campaign:manage"],
  billingCampaignsGenerate: ["billing:campaign:generate"],
  billingCampaignsIssue: ["billing:campaign:issue"],
  billingInvoicesView: [
    "billing:invoice:view",
    "billing:invoice:issue",
    "billing:invoice:cancel",
    "billing:invoice:payment:create",
    "billing:invoice:delivery:create",
  ],
  billingInvoiceIssue: ["billing:invoice:issue"],
  billingInvoiceCancel: ["billing:invoice:cancel"],
  billingInvoicePaymentCreate: ["billing:invoice:payment:create"],
  billingInvoiceDeliveryCreate: ["billing:invoice:delivery:create"],
  billingInvoicesManage: [
    "billing:invoice:issue",
    "billing:invoice:cancel",
    "billing:invoice:payment:create",
    "billing:invoice:delivery:create",
  ],
  settingsView: ["settings:view", "settings:manage"],
  settingsManage: ["settings:manage"],
  utilityPagesView: ["calendar:view", "profile:view"],
  staffUtilities: ["calendar:view", "profile:view"],
} as const;

export function hasAnyPermissionCode(
  permissionCodes: string[] | readonly string[],
  requiredPermissions?: readonly string[]
) {
  if (!requiredPermissions || requiredPermissions.length === 0) return true;
  return requiredPermissions.some((code) => permissionCodes.includes(code));
}
